name: Clone Repository

on:
  workflow_dispatch:


jobs:
  clone_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'BlankTMing/ManifestAutoUpdate'  # 替换为目标仓库的用户名和仓库名
          fetch-depth: 0  # 0 表示克隆所有分支和历史

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Clone all branches
        run: |
          git fetch --all
