name: Clone All Branches

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone all branches
      run: |
        git fetch --all
        for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
          git branch --track ${branch#remotes/origin/} $branch
        done
        git pull --all
