name: Sync Public Repository

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Your Repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Clone Public Repository
      uses: actions/checkout@v2
      with:
        repository: BlankTMing/ManifestAutoUpdate
        ref: 001000001000 # or the branch you want to sync
        path: public-repository

    - name: Merge Public Repository
      run: |
        cd public-repository
        git fetch --all --prune
        git checkout main # or the branch you want to sync
        git merge --no-ff origin/main # or the branch you want to sync
        cd ..
        git add public-repository
        git commit -m "Sync public repository"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main # or the branch you want to sync
