name: Sync Public Repo to Private Repo
 
on:
  push:
    branches:
      - main  # 你的默认分支，或者你想触发同步的分支
 
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          ref: main  # 你想要同步到的分支
 
      - name: Sync Public Repo
        uses: peaceiris/actions-gh-pages-sync@v3
        with:
          # 你的公开仓库的用户名、仓库名和分支
          source_user: BlankTMing
          source_repo: ManifestAutoUpdate
          source_branch: 001000001000
 
          # 如果需要，可以设置GitHub Personal Access Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
