name: Sync with Upstream

on:
  schedule:
    # 每天凌晨执行一次
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取所有分支和提交历史

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git remote add upstream https://github.com/BlankTMing/ManifestAutoUpdate.git # 替换为公开仓库的URL

      - name: Fetch upstream branches
        run: git fetch --all upstream

      - name: Sync branches
        run: |
          # 遍历所有远程分支
          for remote_branch in $(git branch -r upstream | grep -v HEAD); do
            # 提取分支名
            branch_name=${remote_branch#origin/}
            # 检查本地是否存在该分支
            if git show-ref --quiet refs/heads/$branch_name; then
              echo "Branch $branch_name already exists, skipping."
            else
              # 如果不存在，则创建并推送本地分支到远程
              git checkout -b $branch_name upstream/$branch_name
              git push -u origin $branch_name
              echo "Created and pushed branch $branch_name"
            fi
          done
