name: Update M3U File

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download and update file
        run: |
          curl -o o_cn.txt https://m3u.ibert.me/txt/o_cn.txt
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add o_cn.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update m3u file" && git push)
